--- @meta

--- @alias BuiltEvent EventData.on_built_entity|EventData.on_robot_built_entity|EventData.on_entity_cloned|EventData.script_raised_built|EventData.script_raised_revive
--- @alias DestroyedEvent EventData.on_player_mined_entity|EventData.on_robot_mined_entity|EventData.on_entity_died|EventData.script_raised_destroy

---@class LMRecipeData
---@field surface_conditions? SurfaceCondition[]
---@field ingredients? Ingredient[]
---@field results? Product[]
---@field stack_ingredients? Ingredient[]
---@field energy_required? double
---@field category? string
---@field enabled? boolean

---@class LMLoaderTemplate
---@field no_tech? boolean
---@field no_filter? boolean
---@field no_stack? boolean
---@field name? string
---@field localised_name? data.LocalisedString
---@field localised_description? data.LocalisedString
---@field underground_name? string
---@field tint? Color
---@field next_upgrade? string
---@field previous_prefix? string
---@field max_belt_stack_size? int
---@field speed_multiplier? double
---@field energy_type? string
---@field energy_drain? string
---@field energy_per_item? string
---@field order? string
---@field group? string
---@field subgroup? string
---@field recipe_data? LMRecipeData
---@field prerequisite_techs? TechnologyID[]
---@field unlocked_by? string
---@field unit? data.TechnologyUnit